# Generated by Django 4.1.3 on 2023-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wall_anchorsincol_wall_anchorsinrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='bloop',
            field=models.BooleanField(default=False),
        ),
    ]
